"""Add email verification fields

Revision ID: 719464282729
Revises: cb3b302c65c7
Create Date: 2026-07-20 13:53:19.239277

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '719464282729'
down_revision = 'cb3b302c65c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('verification_token', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('verification_token_expires_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('verification_token_expires_at')
        batch_op.drop_column('verification_token')

    # ### end Alembic commands ###
