from app.routes.auth_routes import auth_bp
from app.routes.superadmin_routes import superadmin_bp
from app.routes.admin_routes import admin_bp
from app.routes.customer_routes import customer_bp
from app.routes.product_routes import product_bp
from app.routes.cart_routes import cart_bp
from app.routes.wishlist_routes import wishlist_bp
from app.routes.order_routes import order_bp
from app.routes.payment_routes import payment_bp
